/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DiffsRouteImport } from './routes/diffs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpaceSpacePathRouteRouteImport } from './routes/space/$spacePath/route'
import { Route as SpaceSpacePathIndexRouteImport } from './routes/space/$spacePath/index'
import { Route as SpaceSpacePathTasksRouteImport } from './routes/space/$spacePath/tasks'
import { Route as SpaceSpacePathIssuesRouteImport } from './routes/space/$spacePath/issues'
import { Route as SpaceSpacePathSessionSessionIdRouteImport } from './routes/space/$spacePath/session/$sessionId'
import { Route as SpaceSpacePathIssuesIssueIdRouteImport } from './routes/space/$spacePath/issues/$issueId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffsRoute = DiffsRouteImport.update({
  id: '/diffs',
  path: '/diffs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceSpacePathRouteRoute = SpaceSpacePathRouteRouteImport.update({
  id: '/space/$spacePath',
  path: '/space/$spacePath',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceSpacePathIndexRoute = SpaceSpacePathIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpaceSpacePathRouteRoute,
} as any)
const SpaceSpacePathTasksRoute = SpaceSpacePathTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => SpaceSpacePathRouteRoute,
} as any)
const SpaceSpacePathIssuesRoute = SpaceSpacePathIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => SpaceSpacePathRouteRoute,
} as any)
const SpaceSpacePathSessionSessionIdRoute =
  SpaceSpacePathSessionSessionIdRouteImport.update({
    id: '/session/$sessionId',
    path: '/session/$sessionId',
    getParentRoute: () => SpaceSpacePathRouteRoute,
  } as any)
const SpaceSpacePathIssuesIssueIdRoute =
  SpaceSpacePathIssuesIssueIdRouteImport.update({
    id: '/$issueId',
    path: '/$issueId',
    getParentRoute: () => SpaceSpacePathIssuesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diffs': typeof DiffsRoute
  '/settings': typeof SettingsRoute
  '/space/$spacePath': typeof SpaceSpacePathRouteRouteWithChildren
  '/space/$spacePath/issues': typeof SpaceSpacePathIssuesRouteWithChildren
  '/space/$spacePath/tasks': typeof SpaceSpacePathTasksRoute
  '/space/$spacePath/': typeof SpaceSpacePathIndexRoute
  '/space/$spacePath/issues/$issueId': typeof SpaceSpacePathIssuesIssueIdRoute
  '/space/$spacePath/session/$sessionId': typeof SpaceSpacePathSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diffs': typeof DiffsRoute
  '/settings': typeof SettingsRoute
  '/space/$spacePath/issues': typeof SpaceSpacePathIssuesRouteWithChildren
  '/space/$spacePath/tasks': typeof SpaceSpacePathTasksRoute
  '/space/$spacePath': typeof SpaceSpacePathIndexRoute
  '/space/$spacePath/issues/$issueId': typeof SpaceSpacePathIssuesIssueIdRoute
  '/space/$spacePath/session/$sessionId': typeof SpaceSpacePathSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diffs': typeof DiffsRoute
  '/settings': typeof SettingsRoute
  '/space/$spacePath': typeof SpaceSpacePathRouteRouteWithChildren
  '/space/$spacePath/issues': typeof SpaceSpacePathIssuesRouteWithChildren
  '/space/$spacePath/tasks': typeof SpaceSpacePathTasksRoute
  '/space/$spacePath/': typeof SpaceSpacePathIndexRoute
  '/space/$spacePath/issues/$issueId': typeof SpaceSpacePathIssuesIssueIdRoute
  '/space/$spacePath/session/$sessionId': typeof SpaceSpacePathSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diffs'
    | '/settings'
    | '/space/$spacePath'
    | '/space/$spacePath/issues'
    | '/space/$spacePath/tasks'
    | '/space/$spacePath/'
    | '/space/$spacePath/issues/$issueId'
    | '/space/$spacePath/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diffs'
    | '/settings'
    | '/space/$spacePath/issues'
    | '/space/$spacePath/tasks'
    | '/space/$spacePath'
    | '/space/$spacePath/issues/$issueId'
    | '/space/$spacePath/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/diffs'
    | '/settings'
    | '/space/$spacePath'
    | '/space/$spacePath/issues'
    | '/space/$spacePath/tasks'
    | '/space/$spacePath/'
    | '/space/$spacePath/issues/$issueId'
    | '/space/$spacePath/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiffsRoute: typeof DiffsRoute
  SettingsRoute: typeof SettingsRoute
  SpaceSpacePathRouteRoute: typeof SpaceSpacePathRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diffs': {
      id: '/diffs'
      path: '/diffs'
      fullPath: '/diffs'
      preLoaderRoute: typeof DiffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space/$spacePath': {
      id: '/space/$spacePath'
      path: '/space/$spacePath'
      fullPath: '/space/$spacePath'
      preLoaderRoute: typeof SpaceSpacePathRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space/$spacePath/': {
      id: '/space/$spacePath/'
      path: '/'
      fullPath: '/space/$spacePath/'
      preLoaderRoute: typeof SpaceSpacePathIndexRouteImport
      parentRoute: typeof SpaceSpacePathRouteRoute
    }
    '/space/$spacePath/tasks': {
      id: '/space/$spacePath/tasks'
      path: '/tasks'
      fullPath: '/space/$spacePath/tasks'
      preLoaderRoute: typeof SpaceSpacePathTasksRouteImport
      parentRoute: typeof SpaceSpacePathRouteRoute
    }
    '/space/$spacePath/issues': {
      id: '/space/$spacePath/issues'
      path: '/issues'
      fullPath: '/space/$spacePath/issues'
      preLoaderRoute: typeof SpaceSpacePathIssuesRouteImport
      parentRoute: typeof SpaceSpacePathRouteRoute
    }
    '/space/$spacePath/session/$sessionId': {
      id: '/space/$spacePath/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/space/$spacePath/session/$sessionId'
      preLoaderRoute: typeof SpaceSpacePathSessionSessionIdRouteImport
      parentRoute: typeof SpaceSpacePathRouteRoute
    }
    '/space/$spacePath/issues/$issueId': {
      id: '/space/$spacePath/issues/$issueId'
      path: '/$issueId'
      fullPath: '/space/$spacePath/issues/$issueId'
      preLoaderRoute: typeof SpaceSpacePathIssuesIssueIdRouteImport
      parentRoute: typeof SpaceSpacePathIssuesRoute
    }
  }
}

interface SpaceSpacePathIssuesRouteChildren {
  SpaceSpacePathIssuesIssueIdRoute: typeof SpaceSpacePathIssuesIssueIdRoute
}

const SpaceSpacePathIssuesRouteChildren: SpaceSpacePathIssuesRouteChildren = {
  SpaceSpacePathIssuesIssueIdRoute: SpaceSpacePathIssuesIssueIdRoute,
}

const SpaceSpacePathIssuesRouteWithChildren =
  SpaceSpacePathIssuesRoute._addFileChildren(SpaceSpacePathIssuesRouteChildren)

interface SpaceSpacePathRouteRouteChildren {
  SpaceSpacePathIssuesRoute: typeof SpaceSpacePathIssuesRouteWithChildren
  SpaceSpacePathTasksRoute: typeof SpaceSpacePathTasksRoute
  SpaceSpacePathIndexRoute: typeof SpaceSpacePathIndexRoute
  SpaceSpacePathSessionSessionIdRoute: typeof SpaceSpacePathSessionSessionIdRoute
}

const SpaceSpacePathRouteRouteChildren: SpaceSpacePathRouteRouteChildren = {
  SpaceSpacePathIssuesRoute: SpaceSpacePathIssuesRouteWithChildren,
  SpaceSpacePathTasksRoute: SpaceSpacePathTasksRoute,
  SpaceSpacePathIndexRoute: SpaceSpacePathIndexRoute,
  SpaceSpacePathSessionSessionIdRoute: SpaceSpacePathSessionSessionIdRoute,
}

const SpaceSpacePathRouteRouteWithChildren =
  SpaceSpacePathRouteRoute._addFileChildren(SpaceSpacePathRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiffsRoute: DiffsRoute,
  SettingsRoute: SettingsRoute,
  SpaceSpacePathRouteRoute: SpaceSpacePathRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
